### ISSUE TITLE
How can I stop containers right after automated test finishes?

### ISSUE THREAD

**Issue by MoYummy** [mcherryleigh/protractor-selenium-docker#1]
Hi,

Code clips in this repo are of great help to me! :)

I intend to add e2e test to my CI pipeline.
I would like to know how to detect automation has finished (probably protractor container has exited with 0) and let hub and browser containers exit automatically?

**Comment by mcherryleigh** [comment]
Glad they're helpful. If I understand your question I think you're looking for something like what I have in my travis.yml file + possibly an additional step. Here's an annotated copy of that part of the code.

```
script:
#validating my docker version
  - docker version
#validating my docker-compose version
  - docker-compose version
# starting everything but the test running container with -d so they don't block command line while open
  - docker-compose up -d chrome-swarm
 #validating my docker grid is up and running
  - docker ps -a
# running the test container. Note that we do not use "-d" here so this will block the command line/stuff being run by travis until it finishes. When it finishes the container closes automatically
  - docker-compose up nodejs
```

I made a decision to just let travis tear everything down at the end because this is the *only* thing it was meant to do. However, if you want to stop all other running containers you could add "docker-compose down" to stop all running containers related to the docker-compose file in your current working directory.
